INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right 3rd molar', 'posterior', 1);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right 2nd molar', 'posterior', 2);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right 1st molar', 'posterior', 3);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right 2nd bicuspid', 'posterior', 4);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right 1st bicuspid', 'posterior', 5);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right cuspid', 'anterior', 6);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right lateral incisor', 'anterior', 7);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper right central incisor', 'anterior', 8);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left central incisor', 'anterior', 9);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left lateral incisor', 'anterior', 10);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left cuspid', 'anterior', 11);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left 1st bicuspid', 'posterior', 12);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left 2nd bicuspid', 'posterior', 13);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left 1st molar', 'posterior', 14);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper left 2nd molar', 'posterior', 15);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('upper let 3rd molar', 'posterior', 16);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left 3rd molar', 'posterior', 17);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left 2nd molar', 'posterior', 18);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left 1st molar', 'posterior', 19);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left 1st bicuspid', 'posterior', 20);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left 2nd bicuspid', 'posterior', 21);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left cuspid', 'anterior', 22);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left lateral incisor', 'anterior', 23);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower left central incisor', 'anterior', 24);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right central incisor', 'anterior', 25);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right lateral incisor', 'anterior', 26);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right cuspid', 'anterior', 27);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right 1st bicuspid', 'posterior', 28);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right 2nd bicuspid', 'posterior', 29);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right 1st molar', 'posterior', 30);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right 2nd molar', 'posterior', 31);
INSERT INTO TEETH (DESCRIPTION, CATEGORY, NUMBER) VALUES ('lower right 1st molar', 'posterior', 32);